name: Wordiest
options:
  bundleIdPrefix: com.fsck
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  xcodeVersion: "26.0"

settings:
  base:
    SWIFT_VERSION: "6.0"

packages:
  WordiestCore:
    path: WordiestCore

targets:
  Wordiest:
    type: application
    platform: iOS
    dependencies:
      - package: WordiestCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fsck.wordiest
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "4"
        TARGETED_DEVICE_FAMILY: "1"
        DEVELOPMENT_TEAM: 87WJ58S66M
        CODE_SIGN_ENTITLEMENTS: Wordiest/Wordiest.entitlements
        INFOPLIST_FILE: Wordiest/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    sources:
      - path: Wordiest
        excludes:
          - Resources
      - path: Wordiest/Resources
        buildPhase: resources
    scheme:
      testTargets:
        - WordiestTests
      gatherCoverageData: true

  WordiestTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: Wordiest
      - package: WordiestCore
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    sources:
      - path: WordiestTests
